#!/bin/bash

# Bash script to invoke a PacBio python tool. Python script to be run
# is specified as the first command line parameter. The rest of the
# parameters are passed to the script.

####set -o verbose
set -o errexit
set -o nounset

tools=~skellytf/work/PacBioEDA                           # you'll need to change this

export SEYMOUR_HOME=/is2/projects/pacbio/static/software/smrtanalysis      # and this

export LD_LIBRARY_PATH=${SEYMOUR_HOME}/analysis/lib:${LD_LIBRARY_PATH:=}
export LD_LIBRARY_PATH=${SEYMOUR_HOME}/analysis/lib/atlas:${LD_LIBRARY_PATH:=}
export LD_LIBRARY_PATH=${SEYMOUR_HOME}/common/lib:${LD_LIBRARY_PATH:=}

if [ -d ${SEYMOUR_HOME}/redist/python2.7 ] ; then                  # new python version in 1.3.0?
    export PATH=${SEYMOUR_HOME}/redist/python2.7/bin:${PATH:=}     # use PacBio-supplied python
    export PYTHONPATH=${SEYMOUR_HOME}/analysis/lib/python2.7:${PYTHONPATH:=}
else
    export PATH=${SEYMOUR_HOME}/redist/python2.5/bin:${PATH:=}     # use PacBio-supplied python
    export PYTHONPATH=${SEYMOUR_HOME}/analysis/lib/python2.5:${PYTHONPATH:=}
fi
export PYTHONPATH=$tools:${PYTHONPATH:=}

which=$1
shift

$tools/$which $*

